#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TETROMINO_CELL_SIZE 15

#define GAMEBOARD_START_X 10
#define GAMEBOARD_START_Y 10
#define GAMEBOARD_WIDTH 150
#define GAMEBOARD_HEIGHT 300

#define NEXT_TETROMINO_LABEL_START_X 186
#define NEXT_TETROMINO_LABEL_START_Y 13

#define HOLD_TETROMINO_LABEL_START_X 186
#define HOLD_TETROMINO_LABEL_START_Y 118

#define SCORE_LABEL_START_X 183
#define SCORE_LABEL_START_Y 235

#define SCORE_VALUE_START_X 183
#define SCORE_VALUE_START_Y 250

#endif
